package entity;
// Generated Mar 31, 2018 7:40:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AllotCategory generated by hbm2java
 */
public class AllotCategory  implements java.io.Serializable {


     private Integer allotId;
     private String allotName;
     private String allotCategory;
     private String allotUnit;
     private double allotAmount;
     private int allotQty;
     private Set govtAllotments = new HashSet(0);

    public AllotCategory() {
    }

	
    public AllotCategory(String allotName, String allotCategory, String allotUnit, double allotAmount, int allotQty) {
        this.allotName = allotName;
        this.allotCategory = allotCategory;
        this.allotUnit = allotUnit;
        this.allotAmount = allotAmount;
        this.allotQty = allotQty;
    }
    public AllotCategory(String allotName, String allotCategory, String allotUnit, double allotAmount, int allotQty, Set govtAllotments) {
       this.allotName = allotName;
       this.allotCategory = allotCategory;
       this.allotUnit = allotUnit;
       this.allotAmount = allotAmount;
       this.allotQty = allotQty;
       this.govtAllotments = govtAllotments;
    }
   
    public Integer getAllotId() {
        return this.allotId;
    }
    
    public void setAllotId(Integer allotId) {
        this.allotId = allotId;
    }
    public String getAllotName() {
        return this.allotName;
    }
    
    public void setAllotName(String allotName) {
        this.allotName = allotName;
    }
    public String getAllotCategory() {
        return this.allotCategory;
    }
    
    public void setAllotCategory(String allotCategory) {
        this.allotCategory = allotCategory;
    }
    public String getAllotUnit() {
        return this.allotUnit;
    }
    
    public void setAllotUnit(String allotUnit) {
        this.allotUnit = allotUnit;
    }
    public double getAllotAmount() {
        return this.allotAmount;
    }
    
    public void setAllotAmount(double allotAmount) {
        this.allotAmount = allotAmount;
    }
    public int getAllotQty() {
        return this.allotQty;
    }
    
    public void setAllotQty(int allotQty) {
        this.allotQty = allotQty;
    }
    public Set getGovtAllotments() {
        return this.govtAllotments;
    }
    
    public void setGovtAllotments(Set govtAllotments) {
        this.govtAllotments = govtAllotments;
    }




}


