package entity;
// Generated Mar 31, 2018 7:40:31 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CitizenMaster generated by hbm2java
 */
public class CitizenMaster  implements java.io.Serializable {


     private Integer citiId;
     private String citiName;
     private String citiFather;
     private String citiMother;
     private int citiNid;
     private String citiVillage;
     private String citiPostoff;
     private int citiWard;
     private String citiGender;
     private String citiMStatus;
     private String citiFamiStatus;
     private int citiFamiNumber;
     private String citiOccupation;
     private double citiFamiIncome;
     private String citiBirthDate;
     private String citiAge;
     private String citiDesignation;
     private Set unionStuffs = new HashSet(0);
     private Set unionCabinets = new HashSet(0);
     private Set unionSalaries = new HashSet(0);

    public CitizenMaster() {
    }

	
    public CitizenMaster(String citiName, String citiFather, String citiMother, int citiNid, String citiVillage, String citiPostoff, int citiWard, String citiGender, String citiMStatus, String citiFamiStatus, int citiFamiNumber, String citiOccupation, double citiFamiIncome, String citiBirthDate, String citiAge, String citiDesignation) {
        this.citiName = citiName;
        this.citiFather = citiFather;
        this.citiMother = citiMother;
        this.citiNid = citiNid;
        this.citiVillage = citiVillage;
        this.citiPostoff = citiPostoff;
        this.citiWard = citiWard;
        this.citiGender = citiGender;
        this.citiMStatus = citiMStatus;
        this.citiFamiStatus = citiFamiStatus;
        this.citiFamiNumber = citiFamiNumber;
        this.citiOccupation = citiOccupation;
        this.citiFamiIncome = citiFamiIncome;
        this.citiBirthDate = citiBirthDate;
        this.citiAge = citiAge;
        this.citiDesignation = citiDesignation;
    }
    public CitizenMaster(String citiName, String citiFather, String citiMother, int citiNid, String citiVillage, String citiPostoff, int citiWard, String citiGender, String citiMStatus, String citiFamiStatus, int citiFamiNumber, String citiOccupation, double citiFamiIncome, String citiBirthDate, String citiAge, String citiDesignation, Set unionStuffs, Set unionCabinets, Set unionSalaries) {
       this.citiName = citiName;
       this.citiFather = citiFather;
       this.citiMother = citiMother;
       this.citiNid = citiNid;
       this.citiVillage = citiVillage;
       this.citiPostoff = citiPostoff;
       this.citiWard = citiWard;
       this.citiGender = citiGender;
       this.citiMStatus = citiMStatus;
       this.citiFamiStatus = citiFamiStatus;
       this.citiFamiNumber = citiFamiNumber;
       this.citiOccupation = citiOccupation;
       this.citiFamiIncome = citiFamiIncome;
       this.citiBirthDate = citiBirthDate;
       this.citiAge = citiAge;
       this.citiDesignation = citiDesignation;
       this.unionStuffs = unionStuffs;
       this.unionCabinets = unionCabinets;
       this.unionSalaries = unionSalaries;
    }
   
    public Integer getCitiId() {
        return this.citiId;
    }
    
    public void setCitiId(Integer citiId) {
        this.citiId = citiId;
    }
    public String getCitiName() {
        return this.citiName;
    }
    
    public void setCitiName(String citiName) {
        this.citiName = citiName;
    }
    public String getCitiFather() {
        return this.citiFather;
    }
    
    public void setCitiFather(String citiFather) {
        this.citiFather = citiFather;
    }
    public String getCitiMother() {
        return this.citiMother;
    }
    
    public void setCitiMother(String citiMother) {
        this.citiMother = citiMother;
    }
    public int getCitiNid() {
        return this.citiNid;
    }
    
    public void setCitiNid(int citiNid) {
        this.citiNid = citiNid;
    }
    public String getCitiVillage() {
        return this.citiVillage;
    }
    
    public void setCitiVillage(String citiVillage) {
        this.citiVillage = citiVillage;
    }
    public String getCitiPostoff() {
        return this.citiPostoff;
    }
    
    public void setCitiPostoff(String citiPostoff) {
        this.citiPostoff = citiPostoff;
    }
    public int getCitiWard() {
        return this.citiWard;
    }
    
    public void setCitiWard(int citiWard) {
        this.citiWard = citiWard;
    }
    public String getCitiGender() {
        return this.citiGender;
    }
    
    public void setCitiGender(String citiGender) {
        this.citiGender = citiGender;
    }
    public String getCitiMStatus() {
        return this.citiMStatus;
    }
    
    public void setCitiMStatus(String citiMStatus) {
        this.citiMStatus = citiMStatus;
    }
    public String getCitiFamiStatus() {
        return this.citiFamiStatus;
    }
    
    public void setCitiFamiStatus(String citiFamiStatus) {
        this.citiFamiStatus = citiFamiStatus;
    }
    public int getCitiFamiNumber() {
        return this.citiFamiNumber;
    }
    
    public void setCitiFamiNumber(int citiFamiNumber) {
        this.citiFamiNumber = citiFamiNumber;
    }
    public String getCitiOccupation() {
        return this.citiOccupation;
    }
    
    public void setCitiOccupation(String citiOccupation) {
        this.citiOccupation = citiOccupation;
    }
    public double getCitiFamiIncome() {
        return this.citiFamiIncome;
    }
    
    public void setCitiFamiIncome(double citiFamiIncome) {
        this.citiFamiIncome = citiFamiIncome;
    }
    public String getCitiBirthDate() {
        return this.citiBirthDate;
    }
    
    public void setCitiBirthDate(String citiBirthDate) {
        this.citiBirthDate = citiBirthDate;
    }
    public String getCitiAge() {
        return this.citiAge;
    }
    
    public void setCitiAge(String citiAge) {
        this.citiAge = citiAge;
    }
    public String getCitiDesignation() {
        return this.citiDesignation;
    }
    
    public void setCitiDesignation(String citiDesignation) {
        this.citiDesignation = citiDesignation;
    }
    public Set getUnionStuffs() {
        return this.unionStuffs;
    }
    
    public void setUnionStuffs(Set unionStuffs) {
        this.unionStuffs = unionStuffs;
    }
    public Set getUnionCabinets() {
        return this.unionCabinets;
    }
    
    public void setUnionCabinets(Set unionCabinets) {
        this.unionCabinets = unionCabinets;
    }
    public Set getUnionSalaries() {
        return this.unionSalaries;
    }
    
    public void setUnionSalaries(Set unionSalaries) {
        this.unionSalaries = unionSalaries;
    }




}


