package entity;
// Generated Mar 31, 2018 7:40:31 PM by Hibernate Tools 4.3.1



/**
 * UnionSalary generated by hbm2java
 */
public class UnionSalary  implements java.io.Serializable {


     private Integer salId;
     private CitizenMaster citizenMaster;
     private String citiName;
     private int citiNid;
     private String citiDesignation;
     private double salAmount;

    public UnionSalary() {
    }

    public UnionSalary(CitizenMaster citizenMaster, String citiName, int citiNid, String citiDesignation, double salAmount) {
       this.citizenMaster = citizenMaster;
       this.citiName = citiName;
       this.citiNid = citiNid;
       this.citiDesignation = citiDesignation;
       this.salAmount = salAmount;
    }
   
    public Integer getSalId() {
        return this.salId;
    }
    
    public void setSalId(Integer salId) {
        this.salId = salId;
    }
    public CitizenMaster getCitizenMaster() {
        return this.citizenMaster;
    }
    
    public void setCitizenMaster(CitizenMaster citizenMaster) {
        this.citizenMaster = citizenMaster;
    }
    public String getCitiName() {
        return this.citiName;
    }
    
    public void setCitiName(String citiName) {
        this.citiName = citiName;
    }
    public int getCitiNid() {
        return this.citiNid;
    }
    
    public void setCitiNid(int citiNid) {
        this.citiNid = citiNid;
    }
    public String getCitiDesignation() {
        return this.citiDesignation;
    }
    
    public void setCitiDesignation(String citiDesignation) {
        this.citiDesignation = citiDesignation;
    }
    public double getSalAmount() {
        return this.salAmount;
    }
    
    public void setSalAmount(double salAmount) {
        this.salAmount = salAmount;
    }




}


