package entity;
// Generated Mar 31, 2018 7:40:31 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * UnionCabinet generated by hbm2java
 */
public class UnionCabinet  implements java.io.Serializable {


     private Integer cabiId;
     private CitizenMaster citizenMaster;
     private String citiName;
     private String citiFather;
     private String citiMother;
     private String citiNid;
     private String citiGender;
     private Date citiBirthDate;
     private String citiMStatus;
     private String citiAge;
     private String citiDesignation;

    public UnionCabinet() {
    }

    public UnionCabinet(CitizenMaster citizenMaster, String citiName, String citiFather, String citiMother, String citiNid, String citiGender, Date citiBirthDate, String citiMStatus, String citiAge, String citiDesignation) {
       this.citizenMaster = citizenMaster;
       this.citiName = citiName;
       this.citiFather = citiFather;
       this.citiMother = citiMother;
       this.citiNid = citiNid;
       this.citiGender = citiGender;
       this.citiBirthDate = citiBirthDate;
       this.citiMStatus = citiMStatus;
       this.citiAge = citiAge;
       this.citiDesignation = citiDesignation;
    }
   
    public Integer getCabiId() {
        return this.cabiId;
    }
    
    public void setCabiId(Integer cabiId) {
        this.cabiId = cabiId;
    }
    public CitizenMaster getCitizenMaster() {
        return this.citizenMaster;
    }
    
    public void setCitizenMaster(CitizenMaster citizenMaster) {
        this.citizenMaster = citizenMaster;
    }
    public String getCitiName() {
        return this.citiName;
    }
    
    public void setCitiName(String citiName) {
        this.citiName = citiName;
    }
    public String getCitiFather() {
        return this.citiFather;
    }
    
    public void setCitiFather(String citiFather) {
        this.citiFather = citiFather;
    }
    public String getCitiMother() {
        return this.citiMother;
    }
    
    public void setCitiMother(String citiMother) {
        this.citiMother = citiMother;
    }
    public String getCitiNid() {
        return this.citiNid;
    }
    
    public void setCitiNid(String citiNid) {
        this.citiNid = citiNid;
    }
    public String getCitiGender() {
        return this.citiGender;
    }
    
    public void setCitiGender(String citiGender) {
        this.citiGender = citiGender;
    }
    public Date getCitiBirthDate() {
        return this.citiBirthDate;
    }
    
    public void setCitiBirthDate(Date citiBirthDate) {
        this.citiBirthDate = citiBirthDate;
    }
    public String getCitiMStatus() {
        return this.citiMStatus;
    }
    
    public void setCitiMStatus(String citiMStatus) {
        this.citiMStatus = citiMStatus;
    }
    public String getCitiAge() {
        return this.citiAge;
    }
    
    public void setCitiAge(String citiAge) {
        this.citiAge = citiAge;
    }
    public String getCitiDesignation() {
        return this.citiDesignation;
    }
    
    public void setCitiDesignation(String citiDesignation) {
        this.citiDesignation = citiDesignation;
    }




}


